# Config file for Air - Live Reload for Go

# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Binary file generated
bin = "tmp/main"

# Main file to build
cmd = "go build -o ./tmp/main ."

# Include all directories containing source files
include_ext = ["go", "tmpl", "templ", "tpl", "html"]

# Exclude specific files or directories
exclude_dir = ["assets", "bin", "tmp"]

# Allow to build on .go and .mod file changes
include_dir = ["."]
exclude_file = ["go.sum"]

# Watch these files and trigger a rebuild
watch_dir = ["main", "model", "handler", "view", "posts"]

# Delays
delay = 200 # milliseconds

# Command to execute after building the binary
cmd_args = []

[log]
# Enable logging
level = "debug"
# Log format
format = "text"

[color]
# Terminal colors
main = "cyan"
watcher = "yellow"
error = "red"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

