# Config file for Air - Live Reload for Go

# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Binary file generated
bin = "tmp/main"

# Main file to build
cmd = "go build -o ./tmp/main ."


exclude_dir = ["bin", "tmp"]

include_dir = ["."]
exclude_file = ["go.sum"]

delay = 200 # milliseconds

# Command to execute after building the binary
cmd_args = []

[log]
# Enable logging
level = "debug"
# Log format
format = "text"

[color]
# Terminal colors
main = "cyan"
watcher = "yellow"
error = "red"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

