on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-blog:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-blog:${{ github.sha }}

        - name: 'Update Azure App Service with the new container image'
          run: |
            az webapp config container set \
              --name michelsen-blog \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --docker-custom-image-name ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-blog:${{ github.sha }} \
              --docker-registry-server-url https://${{ secrets.REGISTRY_LOGIN_SERVER }} \
              --docker-registry-server-user ${{ secrets.REGISTRY_USERNAME }} \
              --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}

